---
title: "p8105_hw1_sd3730"
author: "Stacey Dai"
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)
data("penguins", package = "palmerpenguins")
```


# Problem 1

The `penguins` dataset contains information about the measurements of penguins. There are `r nrow(penguins)` rows and `r ncol(penguins)` columns in the dataset. Some important variables include:

- `species`: The species of the penguins, such as `r paste(unique(penguins$species), collapse = ", ")`.
- `island`: The island where the penguins were observed (`r paste(unique(penguins$island), collapse = ", ")`).

Other variables include `bill_length_mm` and `bill_depth_mm`, which describe the length and depth of the bills of penguins in millimeters, respectively. The variable `sex` refers to the gender of the penguins and `year` represents the year that the penguin data was collected. 

The variable `flipper_length_mm` represents the length of the penguins' flippers in millimeters. The mean flipper length is `r mean(penguins$flipper_length_mm, na.rm = TRUE)` mm.





